name: Update README ⭐
on:
  schedule:
    - cron: "45 */6 * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          year: 2022
          userId: 1007744
          leaderboardId: 384168
          sessionCookie: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
